import { useEffect } from "react";
import { LogInWithAnonAadhaar, useAnonAadhaar } from "@anon-aadhaar/react";

export default function AadhaarScanner() {
  const [anonAadhaar] = useAnonAadhaar();

  useEffect(() => {
    if (anonAadhaar.status === "logged-in") {
      console.log("Proof successfully generated by the field agent!");
      
      const proofPayload = {
        proof: anonAadhaar.anonAadhaarProof.proof,
        publicSignals: anonAadhaar.anonAadhaarProof.publicSignals
      };

      console.log("Ready to send to backend:", proofPayload);
    }
  }, [anonAadhaar]);

  return (
    <div className="flex flex-col items-center justify-center p-6 bg-white rounded-lg shadow-md">
      <h2 className="text-xl font-bold mb-4 text-gray-800">
        Verify Aid Recipient
      </h2>
      <p className="text-sm text-gray-600 mb-6 text-center">
        Field Agent: Scan the recipient's Aadhaar QR code to generate a secure proof.
      </p>
      
      <LogInWithAnonAadhaar nullifierSeed={1234} /> 

      {anonAadhaar.status === "logged-in" && (
        <p className="mt-4 text-green-600 font-semibold">
          ✅ Recipient Verified!
        </p>
      )}
    </div>
  );
}