"use client";

import { useEffect, useState } from "react";
import { LogInWithAnonAadhaar, useAnonAadhaar } from "@anon-aadhaar/react";

export default function AadhaarScanner() {
  const [anonAadhaar] = useAnonAadhaar();
  const [hasMounted, setHasMounted] = useState(false);

  // 🟢 STEP 1: Wait for the component to mount in the browser
  useEffect(() => {
    setHasMounted(true);
  }, []);

  useEffect(() => {
    if (anonAadhaar.status === "logged-in") {
      console.log("Proof successfully generated by the field agent!");
      const proofPayload = {
        proof: anonAadhaar.anonAadhaarProof.proof,
        publicSignals: anonAadhaar.anonAadhaarProof.publicSignals
      };
      console.log("Ready to send to backend:", proofPayload);
    }
  }, [anonAadhaar]);

  // 🟢 STEP 2: Return null (or a loader) until we are on the client
  if (!hasMounted) return <div className="p-10 text-zinc-500">Loading Scanner...</div>;

  return (
    <div className="flex flex-col items-center justify-center p-8 bg-zinc-900 border border-zinc-800 rounded-[2rem] shadow-2xl">
      <h2 className="text-xl font-bold mb-4 text-white">
        Verify Aid Recipient
      </h2>
      <p className="text-sm text-zinc-400 mb-8 text-center max-w-[280px]">
        Field Agent: Scan the recipient's Aadhaar QR code to generate a secure proof.
      </p>
      
      <LogInWithAnonAadhaar nullifierSeed={1234} /> 

      {anonAadhaar.status === "logged-in" && (
        <div className="mt-6 flex items-center gap-2 text-emerald-400 font-bold bg-emerald-400/10 px-4 py-2 rounded-full border border-emerald-400/20">
          <span>✅ Recipient Verified</span>
        </div>
      )}
    </div>
  );
}